import { Router } from 'express';
import { profilesRouter } from './profiles';
import { socialRouter } from './social';
import { groupsRouter } from './groups';
import { groupMembersRouter } from './group-members';
import { roomsRouter } from './rooms';
import { groupRoomsRouter } from './group-rooms';
import { roomMembersRouter, myRoomsRouter } from './room-members';
import { postsRouter, userPostsRouter } from './posts';
import { commentsRouter } from './comments';
import { postLikesRouter, commentLikesRouter } from './likes';
import { reactionsRouter } from './reactions';
import { activityRouter } from './activity';
import { documentCommentsRouter } from './documentComments';
import { sectionReviewsRouter, documentReviewsRouter, myReviewsRouter } from './sectionReviews';
import { sectionItemsRouter, myItemsRouter } from './sectionItems';
import { approvalWorkflowsRouter, pendingWorkflowsRouter } from './approvalWorkflows';
import { documentImportExportRouter } from './documentImportExport';

const router = Router();

router.use('/profiles', profilesRouter);
router.use('/social', socialRouter);
router.use('/groups', groupsRouter);
router.use('/groups/:groupId', groupMembersRouter);
router.use('/groups/:groupId/rooms', groupRoomsRouter);
router.use('/rooms', myRoomsRouter);
router.use('/rooms', roomsRouter);
router.use('/rooms/:roomId', roomMembersRouter);
router.use('/rooms/:roomId/posts', postsRouter);
router.use('/posts', userPostsRouter);
router.use('/rooms/:roomId/posts/:postId/comments', commentsRouter);
router.use('/rooms/:roomId/posts/:postId/likes', postLikesRouter);
router.use('/rooms/:roomId/posts/:postId/comments/:commentId/likes', commentLikesRouter);
router.use('/rooms/:roomId/posts/:postId', reactionsRouter);
router.use('/activity', activityRouter);
router.use('/documents', documentCommentsRouter);
router.use('/documents/:documentId/sections/:sectionId/reviews', sectionReviewsRouter);
router.use('/documents/:documentId/reviews', documentReviewsRouter);
router.use('/reviews', myReviewsRouter);
router.use('/documents/:documentId/sections/:sectionId/items', sectionItemsRouter);
router.use('/items', myItemsRouter);
router.use('/documents/:documentId', documentImportExportRouter);
router.use('/documents/:documentId/workflows', approvalWorkflowsRouter);
router.use('/workflows', pendingWorkflowsRouter);

export default router;
