{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lvb.fullname" . }}-coturn
  labels:
    {{- include "lvb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.coturn.credentials.username | b64enc }}
  password: {{ .Values.coturn.credentials.password | b64enc }}
{{- end }}
