apiVersion: v1
kind: Service
metadata:
  name: {{ include "lvb.fullname" . }}-signaling
  labels:
    app: signaling
    {{- include "lvb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: signaling
  ports:
  - port: {{ .Values.signaling.port }}
    targetPort: {{ .Values.signaling.port }}
    protocol: TCP
    name: http
