apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "websocket-gateway.fullname" . }}-config
  labels:
    {{- include "websocket-gateway.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.gateway.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  REDIS_ENDPOINT: {{ include "websocket-gateway.fullname" . }}-redis
  LOCALSTACK_ENDPOINT: http://{{ include "websocket-gateway.fullname" . }}-dynamodb:{{ .Values.dynamodb.port }}
