{{- if .Values.dynamodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket-gateway.fullname" . }}-dynamodb
  labels:
    {{- include "websocket-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: dynamodb
spec:
{{- if .Values.sharedServices.enabled }}
  type: ExternalName
  externalName: {{ .Values.sharedServices.externalName }}
  ports:
    - port: {{ .Values.dynamodb.port }}
      targetPort: {{ .Values.dynamodb.port }}
      protocol: TCP
      name: dynamodb
{{- else }}
  type: ClusterIP
  ports:
    - port: {{ .Values.dynamodb.port }}
      targetPort: dynamodb
      protocol: TCP
      name: dynamodb
  selector:
    {{- include "websocket-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dynamodb
{{- end }}
{{- end }}
