apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket-gateway.fullname" . }}-gateway
  labels:
    {{- include "websocket-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "websocket-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
